## Numpy

In [1]:
# numpy is a numeric python
import numpy as np

In [8]:
# creating 1D arrary from list
x = [10, 20, 30, 40]
arr1 = np.array(x)
arr1

array([10, 20, 30, 40])

In [9]:
# 2D array
arr2 = np.array([[1, 2, 3], [4, 4, 5], [11, 34, 12]])
arr2

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [11, 34, 12]])

##### Array attribute

In [10]:
arr1.shape

(4,)

In [11]:
arr2.shape

(3, 3)

In [12]:
# counting the number of element
arr2.size

9

In [13]:
arr2.ndim

2

##### Array Operation

In [15]:
arr1 + 20

array([30, 40, 50, 60])

In [16]:
y = [15, 18, 20, 30]
y

[15, 18, 20, 30]

In [17]:
arr3 = np.array(y)
arr3

array([15, 18, 20, 30])

In [18]:
arr1 + arr3

array([25, 38, 50, 70])

In [19]:
arr1 * arr3

array([ 150,  360,  600, 1200])

In [20]:
arr2

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [11, 34, 12]])

In [21]:
arr2 + 5

array([[ 6,  7,  8],
       [ 9,  9, 10],
       [16, 39, 17]])

In [22]:
arr2 + [1, 2, 3]

array([[ 2,  4,  6],
       [ 5,  6,  8],
       [12, 36, 15]])

In [24]:
# creating array with inbuilt function
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
# identity matrix
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
# creating array using random function
np.random.random(2)

array([0.04741816, 0.70011513])

In [31]:
np.random.random(5)

array([0.24928419, 0.27275416, 0.06093981, 0.79893724, 0.39834224])

In [29]:
np.random.rand(5, 2)

array([[0.4222372 , 0.06890427],
       [0.09208988, 0.47953962],
       [0.91157257, 0.05340569],
       [0.9853447 , 0.19514478],
       [0.56505726, 0.64138246]])

In [33]:
np.random.randint(1, 10, [3, 3])

array([[9, 8, 8],
       [9, 9, 5],
       [2, 8, 2]])

In [36]:
# seed reproducibility
np.random.seed(22)
np.random.randint(1, 100, [10, 10])

array([[ 5, 45, 65, 85,  9, 96, 94, 19, 15, 46],
       [89, 94, 40, 35, 42,  9, 41,  6, 28, 85],
       [35, 30, 83, 82, 39, 20, 20, 67, 92,  8],
       [28, 24, 24, 12, 95, 14, 53, 76, 48,  2],
       [48, 88, 84, 59, 61, 49, 94, 60, 94, 66],
       [94, 22, 54, 10, 85, 18, 53,  4, 12, 30],
       [97, 83, 68,  7, 80, 61, 29, 33, 90, 54],
       [81, 86, 89, 79, 18, 62,  9, 25, 20, 63],
       [98,  6, 71,  6, 71, 58, 63, 70, 87,  1],
       [63, 50, 82, 19, 90, 97, 64, 52, 86, 72]])

In [37]:
# Array indexing
arr1

array([10, 20, 30, 40])

In [38]:
arr1[1]

20

In [41]:
arr2

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [11, 34, 12]])

In [39]:
arr2[0]

array([1, 2, 3])

In [43]:
arr2[0, 1] # extracting a single number

2

In [44]:
# Slicing in array
arr2[0:2, 0:2]

array([[1, 2],
       [4, 4]])

In [45]:
# modfiying
arr1

array([10, 20, 30, 40])

In [47]:
arr1[1] = 30
arr1

array([10, 30, 30, 40])

In [50]:
# Array manipulation
x = np.random.randint(1, 11, 10)
x

array([9, 3, 7, 6, 7, 7, 8, 8, 5, 5])

In [51]:
x.size

10

In [54]:
y = x.reshape(2, 5) # reshaping
y

array([[9, 3, 7, 6, 7],
       [7, 8, 8, 5, 5]])

In [55]:
# transpose 
y.T

array([[9, 7],
       [3, 8],
       [7, 8],
       [6, 5],
       [7, 5]])

In [56]:
y 

array([[9, 3, 7, 6, 7],
       [7, 8, 8, 5, 5]])

In [60]:
flat = y.flatten()
flat

array([9, 3, 7, 6, 7, 7, 8, 8, 5, 5])

In [63]:
z = np.split(flat, 2)
z

[array([9, 3, 7, 6, 7]), array([7, 8, 8, 5, 5])]

In [64]:
a, b = z

In [65]:
a

array([9, 3, 7, 6, 7])

In [66]:
b

array([7, 8, 8, 5, 5])

In [68]:
# Mathematical operation
value = np.array([1, 4, 9, 16, 25])
np.sqrt(value)

array([1., 2., 3., 4., 5.])

In [70]:
value.sum()

55